[project]
name = "ibsen"
version = "0.5.14.1"
description = "IBS emission of a pulsar+OB-star binary"
authors = [{name = "Lesha"}]
requires-python = ">=3.9"

dependencies = [
    "numpy>=2.0,<3",
    "scipy",
    "astropy",
    "matplotlib",
    "joblib",
    "xarray",
    "naima @ git+https://github.com/zblz/naima.git@ba20a6402e48c89be34ad316ade014f58a43de0c",
]

[project.optional-dependencies]
gui = [
    "PySide6",
    "imageio",
    "imageio-ffmpeg",
]

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools<81", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
ibsen = "ibsen.gui.app:main"
deconstruct-ibsen = "ibsen.gui.dec:main"

[tool.setuptools.package-data]
"ibsen" = ["tab_data/*.nc",
           "absorption/absorp_tab/*.txt",
           "absorption/absorp_tab/*.nc"]


